### ISSUE TITLE
Elements not appearing on initial page load

### ISSUE THREAD

**Issue by Moucky** [scroll-out/scroll-out#51] opened 2020-04-08 20:47 UTC
Every once in a while elements that are in the viewport do not appear when the page is loaded. Elements that are out of view will appear on scroll as expected but the initial elements stay "unscrolled".

I have tried calling ScrollOut in both the window load and DOMContentLoaded events but experience the same result. 

Has anyone else encountered this?

**Comment by ralphhaynes** [comment] 2020-04-24 20:46
@Moucky Has been happening to me on several projects and driving me nuts for months now... Just (maybe) figured out a solution today.

I just had to make sure to set the attribute `data-scroll="in"` on all target elements as well as set `offset: 0` in the ScrollOut props... I was generating the ScrollOut targets dynamically and using the `targets: XXX` prop to fire gsap animations. This way, it seemed the target would assume to be in view and therefore appear instead of the other way around... targets out of view on page load still get `data-scroll="out"` applied when ScrollOut does its thing on page load, so they still trigger as expected.

I my case, I run some javascript to collect the elements I want to animate and add to the ScrollOut targets prop. We typically use WordPress with Elementor and I just like to universally apply some scroll animations without having to manually add/update every single section/widget throughout the whole site.

Would only happen if the page refreshed or loaded not scrolled at the very top of the page. Even if the page loaded  at a scroll position down the page a bit and I scrolled all the way back to the top and back down those elements that were in view when the page loaded (but not appearing) would never appear no matter how much I scrolled or resized the window or anything. Seemed as though if the target was in view when the page loaded it would just never get in to ScrollOut's handler to trigger.

Solution above may just be my unique use case as I haven't tested the method outside of just one project... came across this post as I was searching for a solution, so just thought I'd mention in case it helped you or anybody else

**Comment by notoriousb1t** [comment] 2020-04-26 01:05
I've never experienced this personally, but it sounds like code is removing or adding elements after ScrollOut has already indexed the elements. This can happen when frameworks are replacing elements with new elements or if the page is being loaded dynamically (for example a client-side navigation).

If you only have one scrolling container, try this:
 - On page load (DOMContentLoaded), load ScrollOut without a targets parameter ([data-scroll] is automatically used)
 - on view navigate (including if your framework does some kind of rehydration setp), call .index() and .update() on the ScrollOut instance.

Something like...

```ts
window.addEventListener('DOMContentLoaded', (event) => {
    var scrollOut = ScrollOut();

    myframework.on('viewNavigate', () => {
       scrollOut.index(); 
       scrollOut.update();
    })
});

```

**Comment by Moucky** [comment] 2020-04-27 21:19
Thanks @ralphhaynes, good to know I'm not the only one that's experienced the issue. Also thanks for your input @notoriousb1t, although my setup is very simple. It is essentially this:

```
window.addEventListener('DOMContentLoaded', (event) => {
	ScrollOut({
		once: true,
		threshold: 0.4
	});
});
```

I've tried different settings to see if it would change anything but no luck. I ended up removing the scroll effects until I could figure out the problem. Perhaps next I will try to remove all other JS and see if I still have the issue.

**Comment by rhysjparry** [comment] 2020-05-11 13:06
Yeh i'm also seeing issues in regards to content not being loaded. If I have a lot of content inside a container where the target element is active it will never show as scrolled in when the threshold is set to any value other than 0. I've got a codepen here showing the issue https://codepen.io/rhysjparry/pen/mdeKywG not sure if it's something i've done wrong or it's a genuine issue.

**Comment by Moucky** [comment] 2020-05-11 21:00
@ralphhaynes thanks for the input, that's a great example. I changed the threshold at different screen sizes and sometimes it worked at 0.2 or 0.3 other times nothing showed. I think it must be an issue with the threshold.

**Comment by mattpr** [comment] 2020-05-12 14:06
I've been running into this as well.
Basically elements that are in the viewport at the time of page load often will not have ScrollOut run on them.

```javascript
var elements = document.querySelectorAll('.js-scroll-targets'),
    so;

console.log(elements); // verified.  elements exist in dom at the time they are handed to ScrollOut

so = ScrollOut({
    targets: elements,   // existing elements given directly to ScrollOut
    offset: 0,           // no effect either way
    threshold: 0.5,      // tried setting to 0, no effect
    once: true,
    onChange: function (el, ctx, scrollingElement) {
        console.log('onChange visible = ', ctx.visible, ', ', el); 
    },
    onShown: function (el, ctx, scrollingElement) {
        console.log('onShown visible = ', ctx.visible, ', ', el); 
    },
    onHidden: function (el, ctx, scrollingElement) {
        console.log('onHidden visible = ', ctx.visible, ', ', el); 
    },
});

// page load.  expect to see some console output.

// force index/update after creation.  expect console output...
so.index();
so.update();
// no console output...as if the nodes passed in don't exist?

// doing forcing index/update after a delay does generally 
// solve the issue but is a hack.
window.setTimeout(function () {
    so.index();
    so.update();
    // here (after delay) update gives console output showing state of all nodes...
    // but only if called after index.
},3000);
```

I would love to be able to debug why the element (generally elements that are in viewport on pageload) are not being considered in-view.  None of the event handlers fire.  The element definitely exists.

**Comment by notoriousb1t** [comment] 2020-05-13 06:38
> Yeh i'm also seeing issues in regards to content not being loaded. If I have a lot of content inside a container where the target element is active it will never show as scrolled in when the threshold is set to any value other than 0. I've got a codepen here showing the issue https://codepen.io/rhysjparry/pen/mdeKywG not sure if it's something i've done wrong or it's a genuine issue.

The reason this demo does not work is because 30% of the total area of the element is never in the viewport. From the documentation: (https://scroll-out.github.io/guide.html#configuration)

> The ratio of the element that must be visible before it is marked as visible. Providing the value 0.2 would require 20% of the element to be visible before marking it visible
--

Threshold is not intended for elements that are larger than the viewport. If you would like to suggest a feature based on viewport percentage (which is what I think you actually want), please file a separate bug. It will get really chaotic in this thread trying to solve both the issue you are seeing and the bug that @Moucky has filed. 😄

**Comment by notoriousb1t** [comment] 2020-05-13 06:46
@Moucky, if you are getting the same issue as @rhysjparry, then the reason this doesn't work is because the element's dimensions will never be 30% visible. If that is the case, filing a feature request is the way to go.

**Comment by rhysjparry** [comment] 2020-05-13 08:17
@notoriousb1t ahh that makes sense thank you for explanation!

**Comment by mattpr** [comment] 2020-05-14 08:04
I did some more troubleshooting.  The issue is elements that are in-viewport on initial page load don't have events fired or classes/attributes added to them sometimes.

If I set `once: false` and then scroll the element out of viewport and back in...then the event handlers fire and that element is updated.  This is without calling index again.  

I modified ScrollOut to include more debug output on index/update and ScrollOut reports that this element is indeed in view (`ctx.visible == true`) on page load... so so far I conclude that

- this isn't an issue of elements being dynamically added after scrollout indexes page (I give existing elements directly to scrollout and verified scrollout is supposed to handle NodeList properly).
- this isn't an issue of that element just not being in the viewport when scrollout is initialized (verified ScrollOut sees this element as visible on first index/update calls in `main` (ie the init calls not the `update` calls that are fired in response to scroll or resize window events).

So I am guessing this is just a bug of some sort in the initialization code (the first time these guys run `subscribe`/`loop`/`render`).

I noticed this:
https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L68

```javascript
if (!subscribers.length && clearTask) {
    clearTask = 0;
    cancelAnimationFrame(clearTask);
}
```

Which as I understand it: if we unsubscribe a function and that function was the last function in `subscribers` array (subscribers array now undefined or empty)...*and* clearTask (requestId from `requestAnimationFrame` is not 0)...then we should cancel the last `requestAnimationFrame(loop)` we did.  

However the code sets `clearTask` to `0` before calling `cancelAnimationFrame` which means we are just passing `0` to `cancelAnimationFrame` instead of a real requestId from previous `requestAnimationFrame` call.

Perhaps I missed something here?

**Comment by mattpr** [comment] 2020-05-14 12:33
Okay, I have figured out the problem.

- `subscribe()` and `render()` are run during initialization but before we have run `index()` so there is nothing to do...but a second call to `render()` is queued up via `requestAnimationFrame`.  
    - https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L97
- `update()` is called during init (https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L227)
    - This causes `_changed` and `_changedVisible` in the element `ctx` to be set to `true` for the element that is visible within the viewport.
- When the page finishes loading, the browser fires the `scroll` event which causes `update()` to run a second time.
    - at this point `render()` only ran the first time above (before index/update) `requestAnimationFrame` has not run `render()` a second time (yet).
    - when `update()` runs (this second time) it updates `changedVisible` to `false` on our visible/in-viewport element since the visible status has not changed since the first `update()` run.
- Now our earlier call to `requestAnimationFrame` causes `render()` to run again.
    - Since our `changedVisible` is now `false` (thanks to the second `update()` run), no event handlers are fired and `setAttrs` is not called for the visible element.
    - https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L208
    - *AND* since `once: true` our visible element is removed from `elementContextList` 
    - https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L215

The overall effect is that elements that are in-view (within the viewport) at page load, when set `once:true` may never have attributes updated or event handlers fire.  If you set `once:false` then the event handlers and set attributes will not happen on page load (for in view elements) but if you scroll away and scroll back, then the event handlers will fire since the element was not removed from the `elementContextList` and it has subsequent visibility changes due to scrolling.

**Comment by mattpr** [comment] 2020-05-14 13:04
It looks like the easiest fix for this without doing any cleanup or refactoring is to just remove the initialization of `sub` here: https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L97 in order to not run `render()` for the first time until we have done `index()` and `update()`.

`sub` will be initialized at the end of the `update()` call (https://github.com/scroll-out/scroll-out/blob/master/dist/scroll-out.js#L184) which then causes things to run in the following order:

- `index()`
- `update()`
- `render()` - because index/update have run, attributes and events will fire for elements that are in-view on page load
- `update()` - due to scroll event.  `once: true` elements removed from list...but that's okay because we set attributes and fired events on previous `update()` call.

I'd open a PR but haven't used typescript before and am not sure how you manage building your `dist` directory (ie edit typescript, build `dist` directory and commit the typescript and dist directory changes to git?).

**Comment by mattpr** [comment] 2020-05-14 13:27
I wanted to mention that part of the cause on my end may be that we are setting the `window.location.hash` during page load based on the top in-view section...and setting the hash can trigger a small scroll during page load.  This may be why only some people are running into this issue and also why I have a scroll event firing during page load before first initialized `render()`.

**Comment by Moucky** [comment] 2020-05-14 19:45
@notoriousb1t Sorry, I missed that comment although I believe my issue is different.

**Comment by notoriousb1t** [comment] 2020-05-22 21:37
Thank you for the research @mattpr! 😄  That looks like a pretty nasty bug. 

I think https://github.com/scroll-out/scroll-out/commit/04172f84ffd06b76bfa97e2fe51ba5cd2bd85ea3 should address the initial rendering issue where as https://github.com/scroll-out/scroll-out/commit/a4bf0df9aaa232a2ba582c9ffaf52e67bb90b9ae should address most of the performance issues you identified. @Moucky this has been released as 2.2.10. Please let me know if this solves the intermittent issues.

Also @mattpr, PRs are welcome (even for new features). The way to build dist is to run `npm run build` and the way to run tests is `npm test` or `npm run test:debug` if you want to debug them. I only have a few hours every couple of weeks across my OSS projects for coding nowadays, so I appreciate any help I can get. I know Stephen is equally as busy (perhaps more)

**Comment by mattpr** [comment] 2020-05-22 21:57
Thanks for the reply.  The thing keeping me from a PR (versus a local hack) was (more than lack of typescript experience) that I think to fix this cleanly would require a pretty big refactor of the subscribe/render/loop/update logic.  Pretty fundamental change so I wanted to leave it with you guys to decide how to approach that.

My thinking after some time away from looking at it was that instead of running update every time (init and every onscroll) we should just queue the latest update (disregarding all previous) and only run that update (e.g. dom updates) when render is called by `requestAnimationFrame`.  

This means `requestAnimationFrame` has to do more work when it runs but less code running with the `onscroll` events...and at the same time would guarantee that the dom only gets updated once per render instead of once per scroll...which should resolve this bug.

However, this might create a new bug (depending on how people use ScrollOut) where if someone scrolls quickly down the page they may scroll by elements before the next render fires.  In the example below for instance a user might scroll from A to C quickly and perhaps ScrollOut only updates A and C as being in view because the update when B was in view was overwritten by further onscroll/updates before the next render call.  

But if render isn't running then we can't do work anyway (e.g. to animate that element we scrolled past)...so maybe this would be okay behaviour.  Hard to know without knowing exactly how users are using scrollout.

`
<section id="A"></section>
<section id="B"></section>
<section id="C"></section>
`

**Comment by notoriousb1t** [comment] 2020-05-22 22:19
So with the last commit, here is what we can expect:

Initialization:
 - Guaranteed index, update, render in that order
 - A second, possibly useless render in under 16.666ms (under ideal conditions. People don't usually notice if frames are overbudget until at least 10 frames are skipped)

Scroll/Resize
 - If an update isn't scheduled, it will be scheduled for the next javascript cycle (whenever the browser stops responding to events and timers) Usually this is within a millisecond or so. This should fire prior to render ever firing since that must wait for the next animation frame. If the update results in a change and a render isn't already scheduled, it subscribes which calls render.

So we should be able to expect something like this:

1. 0ms: index
2. 0ms: update
3. 0ms-17ms: render (the classes applied may cause a repaint/reflow)
4. 34ms: unnecessary render

on scroll/resize:
1. 0ms: onUpdate: schedule update
2. 0ms: onUpdate: ignore x 40
3. 2ms: update
4. 19ms: render

It should be physically impossible for a user to notice if something didn't fade in because of fast scrolling unless the performance of the site was already abysmal. The other thing is that the requestAnimationFrame should guarantee priority in modern browsers, so I have serious doubts this will be an issue for users.

**Comment by Moucky** [comment] 2020-05-25 03:55
@notoriousb1t Looks like that's solved it for me! Thanks so much for the hard work you've put in. Also thanks @mattpr for the work debugging. 👍

**Closed** 2020-05-25 04:17 UTC
Labels: bug
